apiVersion: v1
kind: ServiceAccount
metadata:
  name: task-manager-backend
  namespace: task-manager
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::xxx:role/task-manager-backend-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: task-manager-frontend
  namespace: task-manager
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::xxx:role/task-manager-frontend-role
